---
title: "Data Notebook"
format: html
editor: visual
---

Background:

```{r}
#The question that guided this data notebook is determining the amount of children living in poverty in Baltimore City, analyzing it along racial and geographic lines. I will be using two data sets for this project: one called baltcity_income_clean that gives the median household income of each neighborhood in Baltimore City. I will also be using black_population to help determine the Black population in each CSA of Baltimore City. #These data sets were cleaned from US Census data. The US Census Bureau conducts a study every 10 years which counts every resident in the United States, with the most recent one being in 2020. 
```

Library

```{r}
#Loading libraries
library(tidyverse)
library(janitor)
```

1.  What is a summary of the median household income per neighborhood in Baltimore City?

```{r}
balt_income <- read_csv("baltcity_income_clean.csv")
summary(balt_income)
balt_income %>%
  select(Neighborhood,x2020) %>% 
  summarise(
    count_tracts = n(),
    x2020_median = median(x2020, na.rm=TRUE),
    x2020_avg = mean(x2020, na.rm=TRUE),
    min_2020 = min(x2020, na.rm=TRUE),
    max_2020 = max(x2020, na.rm=TRUE)
  ) 
balt_income %>%
  select(Neighborhood, x2020) %>% 
  filter((x2020 ==13559) | (x2020==199531))
#The code above determines the median, mean, minimum and maximum of the median household income of neighborhoods in Baltimore in 2020. The median is $49,875, the mean is $56,311.21, the minimum is $13,559 (which is associated with Upton/Druid Heights) and the maximum income is $199,531 (which is associated with North Baltimore/Guilford/Homeland). I will be looking at the racial makeup of these neighborhoods in later code. 

```

1.  How many neighborhoods in Baltimore City are below the poverty line? 

```{r}
#Based off of the assumption of the neighborhoods making up the median household income being within a four person family,two parents and two children,  with the poverty threshold being $26,200. This was determined by the Census poverty threshold for 2020. 
filter_balt <- balt_income %>% 
  filter(x2020 < 26200 )
top5<- filter_balt %>% 
slice_min(x2020, n=5)
neighborhood_colors <- c("Upton/Druid Heights" = "red",
                         "Sandtown-Winchester/Harlem Park" = "blue",
                         "Southwest Baltimore" = "green",
                         "Oldtown/Middle East" = "orange",
                         "Cherry Hill" = "purple")
top5 %>% 
  ggplot(aes(x = Neighborhood, y = x2020, fill= Neighborhood)) +
  geom_bar(stat = "identity") +
  labs(title = "Five Baltimore City Neighborhoods With the Lowest Median Household Income", 
       subtitle = "Baltimore City data, 2010, 2016 ,2020",
       caption = "Source: Baltimore City (JOUR472 Rob Wells), Graphic by: Ela Jalil",
       y="Neighborhood",
       x="Median Household Income")+
  scale_fill_manual(values = neighborhood_colors)+
  scale_y_continuous(breaks = seq(0, max(top5$x2020), by = 1000))


#For additional context for these five neighborhoods,there are 19 neighborhoods in Baltimore City in 2020 that were below the poverty line. The five neighborhoods with the lowest household median income is Upton/ Druid Heights ($13,559), Sandtown-Winchester/Harlem Park ($13,963), Southwest Baltimore ($14,269), Oldtown/Middle East ($14,304), Cherry Hill ($14,349). The chart that I created shows the five Baltimore City neighborhoods with the lowest median household income. It is evident in this table that these neighborhoods are well in the poverty threshold. 
```

1.  \[What is the Black population in the five neighborhoods with the lowest median household income?

```{r}
#wrap headline
black_population <- read_csv("black_population.csv")
dispo <- black_population %>%  
  filter(CSA2010 %in% c("Upton/Druid Heights", "Sandtown-Winchester/Harlem Park", "Southwest Baltimore", "Oldtown/Middle East", "Cherry Hill")) 

dispo <- dispo %>% 
  select(CSA2010, paa20) 

ggplot(dispo, aes(x = CSA2010, y = paa20, fill = paa20)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(label = paa20), hjust = -0.1, size = 2.5) +
  labs(
    title = str_wrap("Percentage Black population in poorest Baltimore neighborhoods",width=40),
    x = "Neighborhoods",
    y = "Percentage Black Population",
    caption = "Source: US Census Data"
  )
#The five most impoverished neighborhoods in Baltimore City had a majority-Black population as of 2020. Sandtown-Winchester had a 92.5% Black population, Cherry Hill had a 89.1% Black population, Upton/Druid Heights had an 88% Black population, Oldtown/Middle East had a 77.5% Black population and Southwest Baltimore had a 75.2% Black population. 


```

/ 1. What is the child poverty rate in those 5 neighborhoods?

```{r}
poverty_child <- read_csv("poverty_baltimore.csv")
filter_poverty <- poverty_child %>% 
  select(CSA2020, hhchpov20)
dispo_poverty <- filter_poverty %>%  
  filter(CSA2020 %in% c("Upton/Druid Heights", "Sandtown-Winchester/Harlem Park", "Southwest Baltimore", "Oldtown/Middle East", "Cherry Hill"))

dispo_poverty <- dispo_poverty %>% 
  select(CSA2020, hhchpov20) 


#The five neighborhoods in Baltimore City that have the lowest household income and are below the 2020 poverty rate also have relatively high rates of childhood poverty. Oldtown/Middle East is the only neighborhood without a majority percentage of childhood poverty (48.6%), with Cherry Hill having a 51.2% childhood poverty rate, Southwest Baltimore having a 55.5% childhood poverty rate, Sandtown-Winchester/Harlem Park having a 60.5% childhood poverty rate, and Upton/Druid Heights having a 69.8% childhood poverty rate. 
```
